---
- hosts: 172.31.0.150
- tasks:
    - name: Install Python
      shell: yum install python3
    - name: Stop Container
      shell: docker container stop cicd
    - name: Remove Container
      shell: docker container rm cicd
    - name: Remove Docker Image
      shell: docker image rmi amithrx/doc_image
    - name: Create New Container
      shell: docker container run -itd -p 80:80 --name cicd cicd
    
